config/routes.rb
Rails.application.routes.draw do
   get'/blogs', to:'blogs#index'
   
   resources :blogs do
       collection do
           post :confirm
       end
   end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :content, length: { in: 1..140 }, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    before_action :set_blog, only:[:show,:edit,:update, :destroy]
    
  def index
      @blogs = Blog.all
  end
  
  def new
      if params[:back]
          @blog = Blog.new(blog_params)
      else
          @blog = Blog.new
      end
  end
  
  def create
      @blog = Blog.new(blog_params)
      if @blog.save
          redirect_to new_blog_path, notice:"つぶやきを投稿しました"
      else
          render 'new'
      end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
      if @blog.update(blog_params)
          redirect_to blogs_path, notice: "つぶやきを編集しました"
      else
          render 'edit'
      end
  end
  
  def destroy
      @blog.destroy
      redirect_to blogs_path, notice: "つぶやきを削除しました"
  end
  
  def confirm
      @blog = Blog.new(blog_params)
      render :new if @blog.invalid?
  end
      
  private
  
  def blog_params
      params.require(:blog).permit(:content)
  end
  
  def set_blog
      @blog = Blog.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
    def choose_new_or_edit
        if action_name == 'new'||action_name == 'confirm'
            confirm_blogs_path
        elsif action_name == 'edit'
            blog_path
        end
    end
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true, url: choose_new_or_edit) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit "つぶやく" %>
<% end %>

<%= link_to "つぶやき一覧画面にもどる", blogs_path %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、投稿する。</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :content %>

  <p>つぶやき:<%= @blog.content %></p>
  <%= form.submit  "つぶやく" %>
<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :content %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<%= render 'form' %>

app/views/blogs/index.html.erb
<h1>つぶやき一覧</h1>
<br>
<p><%= notice %></p>

<br>
<table>
<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.content %></td>
    <td><%= link_to '詳細を確認する', blog_path(blog.id) %></td>
    <td><%= link_to "つぶやきを編集する", edit_blog_path(blog.id),data: { confirm: '本当に編集していいですか？' } %></td>
    <td><%= link_to 'つぶやきを削除する', blog_path(blog.id), method: :delete,data: { confirm: '本当に削除していいですか？' } %></td>
  </tr>
<% end %>
</table>
<br>
<td><%= link_to 'つぶやきを投稿する',new_blog_path %></td>

app/views/blogs/new.html.erb
<h2>つぶやく</h2>

<%= render 'form' %>

app/views/blogs/show.html.erb
<h1>つぶやき詳細画面</h1>
<p>内容: <%= @blog.content %></p>

<%= link_to "つぶやき一覧画面にもどる", blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twclone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>